language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - 'pypy3'
before_install:
  - pip install poetry
install:
  - poetry install --no-interaction
script:
  - poetry run pylint -E mikrokosmos
  - poetry run pytest -svv --cov=mikrokosmos
